
const winnersList = document.getElementById('winnersList');
const winnersList1 = document.getElementById('winnersList1');
const winnersList2 = document.getElementById('winnersList2');

const winners = [
  " 1901 -Jacobus H.van't Hoff : Netherlands: - Discovered laws of chemical dynamics and osmotic pressure in solutions",
"1902 - Emil Hermann Fischer : Germany: - Synthetic studies of sugar and purine groups",
"1903 - Svante A. Arrhenius : Sweden : - Theory of electrolytic dissociation",
"1904 - Sir William Ramsay : Great Britain :	- Discovered the noble gases",
"1905 - Adolf von Baeyer : Germany :	- Organic dyes and hydroaromatic compounds",
"1906 - Henri Moissan - France - Studied and isolated the element fluorine",
"1907 - Eduard Buchner - Germany - Biochemical studies, discovered fermentation without cells",
"1908 - Sir Ernest Rutherford - Great Britain - Decay of the elements, chemistry of radioactive substances",
"1909 - Wilhelm Ostwald - Germany - Catalysis, chemical equilibria, and reaction rates",
"1910 - Otto Wallach - Germany - Alicyclic compounds",
"1911 - Marie Curie - Poland-France - Discovered radium and polonium",
"1912 - Victor Grignard, Paul Sabatier - France, France - Grignard's reagent, Hydrogenation of organic compounds in the presence of finely divided metals",
"1913 - Alfred Werner - Switzerland - Bonding relations of atoms in molecules (inorganic chemistry)",
"1914 - Theodore W. Richards - United States - Determined atomic weights",
"1915 - Richard M. Willstätter - Germany - Investigated plant pigments, particularly chlorophyll",
"1916 - The prize money was allocated to the Special Fund of this prize section",
"1917 - The prize money was allocated to the Special Fund of this prize section",
"1918 - Fritz Haber - Germany - Synthesized ammonia from its elements",
"1919 - The prize money was allocated to the Special Fund of this prize section",
"1920 - Walther H. Nernst - Germany - Studies on thermodynamics",
"1921 - Frederick Soddy - Great Britain - Chemistry of radioactive substances, occurrence and nature of the isotopes",
"1922 - Francis William Aston - Great Britain - Discovered several isotopes, mass spectrograph",
"1923 - Fritz Pregl - Austria - Microanalysis of organic compounds",
"1924 - The prize money was allocated to the Special Fund of this prize section",
"1925 - Richard A. Zsigmondy - Germany, Austria - Colloid chemistry (ultramicroscope)",
"1926 - Theodor Svedberg - Sweden - Disperse systems (ultracentrifuge)",
"1927 - Heinrich O. Wieland - Germany - Constitution of bile acids",
"1928 - Adolf Otto Reinhold Windaus - Germany - Study of sterols and their relation with vitamins (vitamin D)",
"1929 - Sir Arthur Harden, Hans von Euler-Chelpin - Great Britain, Sweden, Germany - Studied fermentation of sugars and enzymes",
"1930 - Hans Fischer - Germany - Studied blood and plant pigments, synthesized hemin",
"1931 - Friedrich Bergius, Karl Bosch - Germany, Germany - Developed chemical high-pressure processes",
"1932 - Irving Langmuir - United States - Surface chemistry",
"1933 - The prize money was with 1/3 allocated to the Main Fund and with 2/3 to the Special Fund of this prize section",
"1934 - Harold Clayton Urey - United States - Discovery of heavy hydrogen (deuterium)",
"1935 - Frederic Joliot-Curie, Iréne Joliot-Curie - France, France - Syntheses of new radioactive elements (artificial radioactivity)",
"1936 - Peter J. W. Debye - Netherlands, Germany - Studied dipole moments and the diffraction of X rays and electron beams by gases",
"1937 - Walter N. Haworth, Paul Karrer - Great Britain, Switzerland - Studied carbohydrates and vitamin C, Studied carotenoids and flavins and vitamins A and B2",
"1938 - Richard Kuhn - Germany - Studied carotenoids and vitamins",
"1939 - Adolf F. J. Butenandt, Lavoslav Stjepan Ružička - Germany, Switzerland - Studies on sexual hormones, Studied polymethylenes and higher terpenes",
"1940 - The prize money was with 1/3 allocated to the Main Fund and with 2/3 to the Special Fund of this prize section",
"1941 - The prize money was with 1/3 allocated to the Main Fund and with 2/3 to the Special Fund of this prize section",
"1942 - The prize money was with 1/3 allocated to the Main Fund and with 2/3 to the Special Fund of this prize section",
"1943 - Georg de Hevesy - Hungary - Application of isotopes as indicators in the investigation of chemical processes",
"1944 - Otto Hahn - Germany - Discovered nuclear fission of atoms",
"1945 - Artturi Ilmari Virtanen - Finland - Discoveries in the area of agricultural and food chemistry, method of preservation of fodder",
"1946 - James B. Sumner, John H. Northrop, Wendell M. Stanley - United States - Prepared enzymes and virus proteins in pure form, Crystallizability of enzymes",
"1947 - Sir Robert Robinson - Great Britain - Studied alkaloids",
"1948 - Arne W. K. Tiselius - Sweden - Analysis using electrophoresis and adsorption, discoveries concerning serum proteins",
"1949 - William F. Giauque - United States - Contributions to chemical thermodynamics, properties at extremely low temperatures (adiabatic demagnetization)",
"1950 - Kurt Alder, Otto P. H. Diels - Germany, Germany - Developed diene synthesis",
"1951 - Edwin M. McMillan, Glenn T. Seaborg - United States - Discoveries in the chemistry of transuranium elements",
"1952 - Archer J. P. Martin, Richard L. M. Synge - Great Britain, Great Britain - Invented distribution chromatography",
"1953 - Hermann Staudinger - Germany - Discoveries in the area of macromolecular chemistry",
"1954 - Linus C. Pauling - United States - Studied the nature of the chemical bond (molecular structure of proteins)",
"1955 - Vincent du Vigneaud - United States - Synthesized a polypeptide hormone",
"1956 - Sir Cyril Norman Hinshelwood, Nikolai N. Semenov - Great Britain, Soviet Union - Mechanisms of chemical reactions",
"1957 - Sir Alexander R. Todd - Great Britain - Studied nucleotides and their coenzymes",
"1958 - Frederick Sanger - Great Britain - Structure of proteins, especially insulin",
"1959 - Jaroslav Heyrovský - Czech Republic - Polarography",
"1960 - Willard F. Libby - United States - Application of carbon 14 for age determinations (radiocarbon dating)",
"1961 - Melvin Calvin - United States - Studied the assimilation of carbonic acid by plants (photosynthesis)",
"1962 - John C. Kendrew, Max F. Perutz - Great Britain, Great Britain, Austria - Studied the structures of globulin proteins",
"1963 - Giulio Natta, Karl Ziegler - Italy, Germany - Chemistry and technology of high polymers",
"1964 - Dorothy Mary Crowfoot Hodgkin - Great Britain - Structure determination of biologically important substances by means of X rays",
"1965 - Robert B. Woodward - United States - Syntheses of natural products",
"1966 - Robert S. Mulliken - United States - Studied chemical bonds and the electron structure of molecules using the orbital method",
"1967 - Manfred Eigen, Ronald G. W. Norrish, George Porter - Germany, Great Britain, Great Britain - Investigated extremely fast chemical reactions",
"1968 - Lars Onsager - United States, Norway - Studied the thermodynamics of irreversible processes",
"1969 - Derek H. R. Barton, Odd Hassel - Great Britain, Norway - Development of the concept of conformation",
"1970 - Luis F. Leloir - Argentina - Discovery of sugar nucleotides and their role in the biosynthesis of carbohydrates",
"1971 - Gerhard Herzberg - Canada - Electron structure and geometry of molecules, particularly of free radicals (molecular spectroscopy)",
"1972 - Christian B. Anfinsen, Stanford Moore, William H. Stein - United States, United States, United States - Studied ribonuclease (Anfinsen), Studied the active center of ribonuclease (Moore & Stein)",
"1973 - Ernst Otto Fischer, Geoffrey Wilkinson - Germany, Great Britain - Chemistry of metal-organic sandwich compounds",
"1974 - Paul J. Flory - United States - Physical chemistry of macromolecules",
"1975 - John Cornforth, Vladimir Prelog - Australia - Great Britain, Yugoslavia - Switzerland - Stereochemistry of enzyme catalysis reactions, Studied the stereochemistry of organic molecules and reactions",
"1976 - William N. Lipscomb - United States - Structure of boranes",
"1977 - Ilya Prigogine - Belgium - Contributions to the thermodynamics of irreversible processes, particularly to the theory of dissipative structures",
"1978 - Peter Mitchell - Great Britain - Studied biological energy transfer, development of the chemiosmotic theory",
"1979 - Herbert C. Brown, Georg Wittig - United States, Germany - Development of (organic) boron and phosphorous compounds",
"1980 - Paul Berg, Walter Gilbert, Frederick Sanger - United States, United States, Great Britain - Studied the biochemistry of nucleic acids, particularly hybrid DNA (technology of gene surgery) (Berg), Determined base sequences in nucleic acids (Gilbert & Sanger)",
"1981 - Kenichi Fukui, Roald Hoffmann - Japan, United States - Theories on the progress of chemical reactions (frontier orbital theory)",
"1982 - Aaron Klug - South Africa - Developed crystallographic methods for the elucidation of biologically important nucleic acid protein complexes",
"1983 - Henry Taube - Canada - Reaction mechanisms of electron transfer, especially with metal complexes",
"1984 - Robert Bruce Merrifield - United States - Method for the preparation of peptides and proteins",
"1985 - Herbert A. Hauptman, Jerome Karle - United States, United States - Developed direct methods for the determination of crystal structures",
"1986 - Dudley R. Herschbach, Yuan T. Lee, John C. Polanyi - United States, United States, Canada - Dynamics of chemical elementary processes",
"1987 - Donald James Cram, Charles J. Pedersen, Jean-Marie Lehn - United States, United States, France - Development of molecules with structurally specific interaction of high selectivity",
"1988 - Johann Deisenhofer, Robert Huber, Hartmut Michel - Germany, Germany, Germany - Determined the three-dimensional structure of a photosynthetic reaction center",
"1989 - Thomas Robert Cech, Sidney Altman - United States, United States - Discovered the catalytic properties of ribonucleic acid (RNA)",
"1990 - Elias James Corey - United States - Developed novel methods for the synthesis of complex natural compounds (retrosynthetic analysis)",
"1991 - Richard R. Ernst - Switzerland - Developed high resolution nuclear magnetic resonance spectroscopy (NMR)",
"1992 - Rudolph A. Marcus - Canada - United States - Theories of electron transfer",
"1993 - Kary B. Mullis, Michael Smith - United States, Great Britain - Invention of the polymerase chain reaction (PCR), Development of site-specific mutagenesis",
"1994 - George A. Olah - United States - Carbocations",
"1995 - Paul Crutzen, Mario Molina, F. Sherwood Rowland - Netherlands, Mexico - United States - Work in atmospheric chemistry, particularly concerning the formation and decomposition of ozone",
"1996 - Harold W. Kroto, Robert F. Curl, Jr., Richard E. Smalley - Great Britain, United States, United States - Discovered fullerenes",
"1997 - Paul Delos Boyer, John E. Walker, Jens C. Skou - United States, Great Britain, Denmark - Elucidated the enzymatic mechanism underlying the synthesis of adenosine triphosphate (ATP), First discovery of an ion-transporting enzyme, Na+, K+-ATPase",
"1998 - Walter Kohn, John A. Pople - United States, Great Britain - Development of the density-functional theory (Kohn), Development of computational methods in quantum chemistry (GAUSSIAN computer programs) (Pople)",
"1999 - Ahmed H. Zewail - Egypt, United States - Studied the transition states of chemical reactions using femtosecond spectroscopy",
"2000 - Alan J. Heeger, Alan G. MacDiarmid, Hideki Shirakawa - United States, United States, Japan - Discovered and developed conductive polymers",
"2001 - William S. Knowles, Ryoji Noyori, Karl Barry Sharpless - United States, Japan, United States - Work on chirally catalyzed hydrogenation reactions (Knowles & Noyori), Work on chirally catalyzed oxidation reactions (Sharpless)",
"2002 - John Bennett Fenn, Jokichi Takamine, Kurt Wüthrich - United States, Japan, Switzerland - Developed soft desorption ionization methods for mass spectrometric analyses of biological macromolecules (Fenn & Tanaka), Developed nuclear magnetic resonance spectroscopy for determining the three-dimensional structure of biological macromolecules in solution (Wüthrich)",
"2003 - Peter Agre, Roderick MacKinnon - United States - Discovered water channels for transport of water in cell membranes, Performed structural and mechanistic studies of ion channels in cells",
"2004 - Aaron Ciechanover, Avaram Hershko, Irwin Rose - Israel, Israel, United States - Discovered and elucidated the process of ubiquitin-mediated protein degradation",
"2005 - Yves Chauvin, Robert H. Grubbs, Richard R. Schrock - France, United States, United States - Developed the metathesis method of organic synthesis, allowing for advances in 'green' chemistry",
"2006 - Roger D. Kornberg - United States - For his studies of the molecular basis of eukaryotic transcription",
"2007 - Gerhard Ertl - Germany - For his studies of chemical processes on solid surfaces",
"2008 - Shimomura Osamu, Martin Chalfie, Roger Y. Tsien - United States - For the discovery and development of the green fluorescent protein, GFP",
"2009 - Venkatraman Ramakrishnan, Thomas A. Steitz, Ada E. Yonath - United Kingdom, United States, Isreal - For studies of the structure and function of the ribosome",
   
];


const winners1 = [
"1901 -Wilhelm Conrad Röntgen : Germany : discovery of X-rays",
"1902 - Hendrik Antoon Lorentz : Netherlands : investigation of the influence of magnetism on radiation",
       "Pieter Zeeman : Netherlands : investigation of the influence of magnetism on radiation",
"1903 - Henri Becquerel : France : discovery of spontaneous radioactivity",
       "Marie Curie : France : investigations of radiation phenomena discovered by Becquerel",
       "Pierre Curie : France : investigations of radiation phenomena discovered by Becquerel",
"1904 - Lord Rayleigh : U.K. : discovery of argon",
"1905 - Philipp Lenard : Germany : research on cathode rays",
"1906 - Sir J.J. Thomson : U.K. : researches into electrical conductivity of gases",
"1907 - A.A. Michelson : U.S. : spectroscopic and metrological investigations",
"1908 - Gabriel Lippmann : France : photographic reproduction of colours",
"1909 - Ferdinand Braun : Germany : development of wireless telegraphy",
       "Guglielmo Marconi : Italy : development of wireless telegraphy",
"1910 - Johannes Diederik van der Waals : Netherlands : research concerning the equation of state of gases and liquids",
"1911 - Wilhelm Wien : Germany : discoveries regarding laws governing heat radiation",
"1912 - Nils Dalén : Sweden : invention of automatic regulators for lighting coastal beacons and light buoys",
"1913 - Heike Kamerlingh Onnes : Netherlands : investigation into the properties of matter at low temperatures; production of liquid helium ",      
"1914 - Max von Laue : Germany : discovery of diffraction of X-rays by crystals",
"1915 - Sir Lawrence Bragg : U.K. : analysis of crystal structure by means of X-rays",
       "Sir William Bragg : U.K. : analysis of crystal structure by means of X-rays",
"1917 - Charles Glover Barkla : U.K. : discovery of characteristic X-radiation of elements",
"1918 - Max Planck : Germany : discovery of the elemental quanta",
"1919 - Johannes Stark : Germany : discovery of the Doppler effect in positive ion rays and division of spectral lines in an electric field",
"1920 - Charles Édouard Guillaume : Switzerland : discovery of anomalies in alloys",
"1921 - Albert Einstein : Switzerland : work in theoretical physics",
"1922 - Niels Bohr : Denmark : investigation of atomic structure and radiation",
"1923 - Robert Andrews Millikan : U.S. : work on elementary electric charge and the photoelectric effect",
"1924 - Karl Manne Georg Siegbahn : Sweden : work in X-ray spectroscopy",
"1925 - James Franck : Germany : discovery of the laws governing the impact of an electron upon an atom",
       "Gustav Hertz : Germany : discovery of the laws governing the impact of an electron upon an atom",
"1926 - Jean Perrin : France : work on the discontinuous structure of matter",
"1927 - Arthur Holly Compton : U.S. : discovery of wavelength change in diffused X-rays",
       "C.T.R. Wilson : U.K. : method of making visible the paths of electrically charged particles",
"1928 - Sir Owen Willans Richardson : U.K. : work on electron emission by hot metals",
"1929 - Louis de Broglie : France : discovery of the wave nature of electrons",
"1930 - Sir Chandrasekhara Venkata Raman : India : work on light diffusion; discovery of the Raman effect",
"1932 - Werner Heisenberg : Germany : creation of quantum mechanics",
"1933 - P.A.M. Dirac : U.K. : introduction of wave equations in quantum mechanics",
       "Erwin Schrödinger : Austria : introduction of wave equations in quantum mechanics",
"1935 - Sir James Chadwick : U.K. : discovery of the neutron",
"1936 - Carl David Anderson : U.S. : discovery of the positron",
       "Victor Francis Hess : Austria : discovery of cosmic radiation",
"1937 - Clinton Joseph Davisson : U.S. : experimental demonstration of the interference phenomenon in crystals irradiated by electrons",
       "Sir George Paget Thomson : U.K. : experimental demonstration of the interference phenomenon in crystals irradiated by electrons",
"1938 - Enrico Fermi : Italy : disclosure of artificial radioactive elements produced by neutron irradiation",
"1939 - Ernest Orlando Lawrence : U.S. : invention of the cyclotron1943 - Otto Stern : U.S. : discovery of the magnetic moment of the proton",
"1944 - Isidor Isaac Rabi : U.S. : resonance method for registration of various properties of atomic nuclei",
"1945 - Wolfgang Pauli : Austria : discovery of the exclusion principle of electrons",
"1946 - Percy Williams Bridgman : U.S. : discoveries in the domain of high-pressure physics",
"1947 - Sir Edward Victor Appleton : U.K. : discovery of the Appleton layer in the upper atmosphere",
"1948 - Patrick M.S. Blackett : U.K. : discoveries in the domain of nuclear physics and cosmic radiation",
"1949 - Yukawa Hideki : Japan : prediction of the existence of mesons",
"1950 - Cecil Frank Powell : U.K. : photographic method of studying nuclear processes; discoveries concerning mesons",
"1951 - Sir John Douglas Cockcroft : U.K. : work on transmutation of atomic nuclei by accelerated particles",
        "Ernest Thomas Sinton Walton : Ireland : work on transmutation of atomic nuclei by accelerated particles",
"1952 - Felix Bloch : U.S. : discovery of nuclear magnetic resonance in solids",
       "E.M. Purcell : U.S. : discovery of nuclear magnetic resonance in solids",
"1953 - Frits Zernike : Netherlands : method of phase-contrast microscopy",
"1954 - Max Born : U.K. : statistical studies of atomic wave functions",
      "Walther Bothe : West Germany : invention of the coincidence method",
"1955 - Polykarp Kusch : U.S. : measurement of the magnetic moment of the electron",
      "Willis Eugene Lamb, Jr. : U.S. : discoveries in the hydrogen spectrum",
"1956 - John Bardeen : U.S. : investigations on semiconductors and invention of the transistor",
      "Walter H. Brattain : U.S. : investigations on semiconductors and invention of the transistor",
      "William B. Shockley : U.S. : investigations on semiconductors and invention of the transistor",
"1957 - Tsung-Dao Lee : China : discovery of violations of the principle of parity",
      "Chen Ning Yang : China : discovery of violations of the principle of parity",
"1958 - Pavel Alekseyevich Cherenkov : U.S.S.R. : discovery and interpretation of the Cherenkov effect",
      "Ilya Mikhaylovich Frank : U.S.S.R. : discovery and interpretation of the Cherenkov effect",
      "Igor Yevgenyevich Tamm : U.S.S.R. : discovery and interpretation of the Cherenkov effect",
"1959 - Owen Chamberlain : U.S. : confirmation of the existence of the antiproton",
      "Emilio Segrè : U.S. : confirmation of the existence of the antiproton",
"1960 - Donald A. Glaser : U.S. : development of the bubble chamber",
"1961 - Robert Hofstadter : U.S. : determination of the shape and size of atomic nucleons",
      "Rudolf Ludwig Mössbauer : West Germany : discovery of the Mössbauer effect",
"1962 - Lev Davidovich Landau : U.S.S.R. : contributions to the understanding of condensed states of matter",
"1963 - J. Hans D. Jensen : West Germany : development of the shell model theory of the structure of atomic nuclei",
      "Maria Goeppert Mayer : U.S. : development of the shell model theory of the structure of atomic nuclei",
      "Eugene Paul Wigner : U.S. : principles governing interaction of protons and neutrons in the nucleus",
"1964 - Nikolay Gennadiyevich Basov : U.S.S.R. : work in quantum electronics leading to construction of instruments based on maser-laser principles",
      "Aleksandr Mikhaylovich Prokhorov : U.S.S.R. : work in quantum electronics leading to construction of instruments based on maser-laser principles",
      "Charles Hard Townes : U.S. : work in quantum electronics leading to construction of instruments based on maser-laser principles",
"1965 - Richard P. Feynman : U.S. : basic principles of quantum electrodynamics",
      "Julian Seymour Schwinger : U.S. : basic principles of quantum electrodynamics",
      "Tomonaga Shin'ichiro : Japan : basic principles of quantum electrodynamics",
"1966 - Alfred Kastler : France : discovery of optical methods for studying Hertzian resonances in atoms",
"1967 - Hans Albrecht Bethe : U.S. : discoveries concerning the energy production of stars",
"1968 - Luis W. Alvarez : U.S. : work with elementary particles, discovery of resonance states",
"1969 - Murray Gell-Mann : U.S. : classification of elementary particles and their interactions",
"1970 - Hannes Alfvén : Sweden : work in magnetohydrodynamics and in antiferromagnetism and ferrimagnetism",
       "Louis-Eugène-Félix Néel : France : work in magnetohydrodynamics and in antiferromagnetism and ferrimagnetism",
"1971 - Dennis Gabor : U.K. : invention of holography",
"1972 - John Bardeen : U.S. : development of the theory of superconductivity",
       "Leon N. Cooper : U.S. : development of the theory of superconductivity",
       "John Robert Schrieffer : U.S. : development of the theory of superconductivity",
"1973 - Leo Esaki : Japan : tunneling in semiconductors and superconductors",
       "Ivar Giaever : U.S. : tunneling in semiconductors and superconductors",
       "Brian D. Josephson : U.K. : tunneling in semiconductors and superconductors",
"1974 - Antony Hewish : U.K. : work in radio astronomy",
       "Sir Martin Ryle : U.K. : work in radio astronomy",
"1975 - Aage N. Bohr : Denmark : work on the atomic nucleus that paved the way for nuclear fusion",
       "Ben R. Mottelson : Denmark : work on the atomic nucleus that paved the way for nuclear fusion",
       "James Rainwater : U.S. : work on the atomic nucleus that paved the way for nuclear fusion",
"1976 - Burton Richter : U.S. : discovery of a new class of elementary particles (psi, or J)",
       "Samuel C.C. Ting : U.S. : discovery of a new class of elementary particles (psi, or J)",
"1977 - Philip W. Anderson : U.S. : contributions to understanding the behavior of electrons in magnetic, noncrystalline solids",
       "Sir Nevill F. Mott : U.K. : contributions to understanding the behavior of electrons in magnetic, noncrystalline solids",
       "John H. Van Vleck : U.S. : contributions to understanding the behavior of electrons in magnetic, noncrystalline solids",
"1978 - Pyotr Leonidovich Kapitsa : U.S.S.R. : invention and application of a helium liquefier",
       "Arno Penzias : U.S. : discovery of cosmic microwave background radiation, providing support for the big-bang theory",
       "Robert Woodrow Wilson : U.S. : discovery of cosmic microwave background radiation, providing support for the big-bang theory",
"1979 - Sheldon Lee Glashow : U.S. : unification of electromagnetism and the weak interactions of subatomic particles",
       "Abdus Salam : Pakistan : unification of electromagnetism and the weak interactions of subatomic particles",
       "Steven Weinberg : U.S. : unification of electromagnetism and the weak interactions of subatomic particles",
"1980 - James Watson Cronin : U.S. : demonstration of simultaneous violation of both charge-conjugation and parity-inversion symmetries",
       "Val Logsdon Fitch : U.S. : demonstration of simultaneous violation of both charge-conjugation and parity-inversion symmetries",
"1981 - Nicolaas Bloembergen : U.S. : applications of lasers in spectroscopy",
       "Arthur Leonard Schawlow : U.S. : applications of lasers in spectroscopy",
       "Kai Manne Börje Siegbahn : Sweden : electron spectroscopy for chemical analysis",
"1982 - Kenneth Geddes Wilson : U.S. : analysis of continuous phase transitions",
"1983 - Subrahmanyan Chandrasekhar : U.S. : contributions to understanding the evolution and devolution of stars",
       "William A. Fowler : U.S. : contributions to understanding the evolution and devolution of stars",
"1984 - Simon van der Meer : Netherlands : discovery of subatomic particles W and Z, which supports the electroweak theory",
       "Carlo Rubbia : Italy : discovery of subatomic particles W and Z, which supports the electroweak theory",
"1985 - Klaus von Klitzing : West Germany : discovery of the quantized Hall effect, permitting exact measurements of electrical resistance",
"1986 - Gerd Binnig : West Germany : development of electron microscopes",
       "Heinrich Rohrer : Switzerland : development of electron microscopes",
       "Ernst Ruska : West Germany : development of electron microscopes",
"1987 - J. Georg Bednorz : West Germany : discovery of new superconducting materials",
       "Karl Alex Müller : Switzerland : discovery of new superconducting materials",
"1988 - Leon Max Lederman : U.S. : research in subatomic particles",
       "Melvin Schwartz : U.S. : research in subatomic particles",
       "Jack Steinberger : U.S. : research in subatomic particles",
"1989 - Hans Georg Dehmelt : U.S. : development of methods to isolate atoms and subatomic particles for study",
       "Wolfgang Paul : West Germany : development of methods to isolate atoms and subatomic particles for study",
       "Norman Foster Ramsey : U.S. : development of the atomic clock",
"1990 - Jerome Isaac Friedman : U.S. : discovery of quarks",
       "Henry Way Kendall : U.S. : discovery of quarks",
       "Richard E. Taylor : Canada : discovery of quarks",
"1991 - Pierre-Gilles de Gennes : France : discovery of general rules for behavior of molecules",
"1992 - Georges Charpak : France : invention of a detector that traces subatomic particles",
"1993 - Russell Alan Hulse : U.S. : identifying binary pulsars",
       "Joseph H. Taylor, Jr. : U.S. : identifying binary pulsars",
"1994 - Bertram N. Brockhouse : Canada : development of neutron-scattering techniques",
       "Clifford G. Shull : U.S. : development of neutron-scattering techniques",
"1995 - Martin Lewis Perl : U.S. : discovery of the tau subatomic particle",
       "Frederick Reines : U.S. : discovery of the neutrino",
"1996 - David M. Lee : U.S. : discovery of superfluidity in the isotope helium-3",
       "Douglas D. Osheroff : U.S. : discovery of superfluidity in the isotope helium-3",
       "Robert C. Richardson : U.S. : discovery of superfluidity in the isotope helium-3",
"1997 - Steven Chu : U.S. : process of trapping atoms with laser cooling",
       "Claude Cohen-Tannoudji : France : process of trapping atoms with laser cooling",
       "William D. Phillips : U.S. : process of trapping atoms with laser cooling",
"1998 - Robert B. Laughlin : U.S. : discovery of the fractional quantum Hall effect",
       "Horst L. Störmer : U.S. : discovery of the fractional quantum Hall effect",
       "Daniel C. Tsui : U.S. : discovery of the fractional quantum Hall effect",
"1999 - Gerardus 't Hooft : Netherlands : study of the quantum structure of electroweak interactions",
       "Martinus J.G. Veltman : Netherlands : study of the quantum structure of electroweak interactions",
"2000 - Zhores I. Alferov : Russia : development of fast semiconductors for use in microelectronics",
       "Jack S. Kilby : U.S. : development of the integrated circuit (microchip)",
       "Herbert Kroemer : Germany : development of fast semiconductors for use in microelectronics",
"2001 - Eric A. Cornell : U.S. : achievement of Bose-Einstein condensation in dilute gases of alkali atoms; early fundamental studies of the properties of the condensates",
       "Wolfgang Ketterle : Germany : achievement of Bose-Einstein condensation in dilute gases of alkali atoms; early fundamental studies of the properties of the condensates",
       "Carl E. Wieman : U.S. : achievement of Bose-Einstein condensation in dilute gases of alkali atoms; early fundamental studies of the properties of the condensates",
"2002 - Raymond Davis, Jr. : U.S. : detection of neutrinos",
       "Riccardo Giacconi : U.S. : seminal discoveries of cosmic sources of X-rays",
       "Koshiba Masatoshi : Japan : detection of neutrinos",
"2003 - Alexei A. Abrikosov : U.S. : discoveries regarding superconductivity and superfluidity at very low temperatures",
       "Vitaly L. Ginzburg : Russia : discoveries regarding superconductivity and superfluidity at very low temperatures",
       "Anthony J. Leggett : U.S. : discoveries regarding superconductivity and superfluidity at very low temperatures",
"2004 - David J. Gross : U.S. : discovery of asymptotic freedom in the theory of the strong interaction",
       "H. David Politzer : U.S. : discovery of asymptotic freedom in the theory of the strong interaction",
       "Frank Wilczek : U.S. : discovery of asymptotic freedom in the theory of the strong interaction",
"2005 - Roy J. Glauber : U.S. : contributions to the field of optics",
       "John L. Hall : U.S. : contributions to the development of laser spectroscopy",
       "Theodor W. Hänsch : Germany : contributions to the development of laser spectroscopy",
"2006 - John C. Mather : U.S. : discovery of the blackbody form and anisotropy of the cosmic microwave background radiation",
       "George F. Smoot : U.S. : discovery of the blackbody form and anisotropy of the cosmic microwave background radiation",
"2007 - Albert Fert : France : discovery of giant magnetoresistance",
       "Peter Grünberg : Germany : discovery of giant magnetoresistance",
"2008 - Kobayashi Makoto : Japan : discovery of the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature",
       "Maskawa Toshihide : Japan : discovery of the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature",
       "Yoichiro Nambu : U.S. : discovery of the mechanism of spontaneous broken symmetry in subatomic physics",
"2009 - Willard Boyle : Canada/U.S. : invention of the CCD sensor, an imaging semiconductor circuit",
       "Charles Kao : U.K./U.S. : achievements concerning the transmission of light in fibers for optical communication",
       "George E. Smith : U.S. : invention of the CCD sensor, an imaging semiconductor circuit",
"2010 - Andre Geim : Netherlands : experiments regarding the two-dimensional material graphene",
       "Konstantin Novoselov : Russia/U.K. : experiments regarding the two-dimensional material graphene",
"2011 - Saul Perlmutter : U.S. : discovery of the accelerating expansion of the universe through observations of distant supern",
]

const winners2 = [
"Emil Adolf von Behring	Germany (1901)	Serum therapy",
       "Sir Ronald Ross	UK (1902)	Worked on malaria",
       "Ivan Petrovich Pavlov	Russia (1904)	Physiology of digestion",
       "Albrecht Kossel	Germany (1910)	Cell Chemistry",
       "Allvar Gullstrand	Sweden (1911)	Dioptrics of the eye",
       "Alexis Carrel	France (1912)	Vascular suture and the transplantation of blood vessels and organs",
       "Archibald Vivian Hill	UK (1922)	Production of heat in the muscle",
       "Sir Frederick Grant Banting & John James Rickard Macleod	Canada & UK (1923)	Discovery of insulin",
       "Karl Landsteiner	Austria (1930)	Discovery of human blood groups",
       "Thomas Hunt Morgan	US (1933)	Role played by the chromosome in heredity",
       "Carl Peter Henrik Dam	Denmark (1943)	Discovery of vitamin K",
       "Sir Alexander Fleming	UK (1945)	Discovery of penicillin and its curative effect in various infectious diseases",
       "Sir Ernst Boris Chain	UK (1945)",
       "Howard Walter Florey	Austria (1945)",
       "Carl Ferdinand Cori	US (1947)	Discovery of the course of the catalytic conversion of glycogen",
       "Gerty Theresa Cori, née Radnitz",		
       "Max Theiler	South Africa (1951)	Yellow fever",
       "Selman Abraham Waksman	US (1952)	Discovery of streptomycin, the first antibiotic effective against tuberculosis",
       "Joshua Lederberg	US (1958)	Genetic recombination",
       "Peyton Rous	US (1966)	Discovery of tumor-inducing viruses",
       "Charles Brenton Huggins	US (1966)	Hormonal treatment of prostatic cancer",
       "Har Gobind Khorana	India & US (1968)	Interpretation of the genetic code and its function in protein synthesis",
       "Marshall W. Nirenberg	US (1968)",
       "Robert W. Holley	US (1968)",
       "Albert Claude	Belgium (1974)	Structural and functional organization of the cell",
       "Christian de Duve",
       "George E. Palade	Romania (1974)",
       "Baruch S. Blumberg	US (1976)	Origin and dissemination of infectious diseases",
       "D. Carleton Gajdusek",
       "Michael S. Brown	US (1985)	Regulation of cholesterol metabolism",
       "Joseph L. Goldstein",
       "Sir Richard J. Roberts	UK (1993)	Discovery of split genes",
       "Phillip A. Sharp	US (1993)",
       "Paul Lauterbur	US (2003)	Magnetic resonance imaging",
       "Sir Peter Mansfield	UK (2003)",
       "Andrew Z. Fire	US (2006)	Discovery of RNA interference",
       "Craig C. Mello",
       "Harald zur Hausen	Germany (2008)	Human papilloma viruses causing cervical cancer",
       "Françoise Barré-Sinoussi	France (2008)	Discovery of human immunodeficiency virus",
       "Luc Montagnier",
       "Sir Robert G. Edwards	UK (2010)	Development of in vitro fertilization",
       "Tu Youyou	China (2015)	Discovery of a novel therapy against Malaria",
       "Yoshinori Ohsumi	Japan (2016)	Mechanisms for autophagy",
  
]

winners.forEach(winner => {
  const listItem = document.createElement('li');
  listItem.textContent = winner;
  winnersList.appendChild(listItem);
});


winners1.forEach(winner => {
  const listItem = document.createElement('li');
  listItem.textContent = winner;
  winnersList1.appendChild(listItem);
});


winners2.forEach(winner => {
  const listItem = document.createElement('li');
  listItem.textContent = winner;
  winnersList2.appendChild(listItem);
});








